# Generated by Django 4.2.5 on 2023-09-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myAppSearch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="slug",
            field=models.SlugField(default="default-slug", unique=True),
        ),
    ]
