# Generated by Django 4.2.5 on 2023-09-15 04:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myAppSearch", "0004_alter_students_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="slug",
        ),
    ]
